// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASZP2BLI48gopNo8OC-06oZYWruttOMc',
    appId: '1:165484821166:web:92efe1adbc5f5c86204b3f',
    messagingSenderId: '165484821166',
    projectId: 'flutter-chatbot-ia',
    authDomain: 'flutter-chatbot-ia.firebaseapp.com',
    storageBucket: 'flutter-chatbot-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy8K8gQLgegAbC590CRlWdDHu_aQe5yKU',
    appId: '1:165484821166:android:3b0a713a6ede9731204b3f',
    messagingSenderId: '165484821166',
    projectId: 'flutter-chatbot-ia',
    storageBucket: 'flutter-chatbot-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzQlIkGMN8lk1wj1YO6aBLsBaiqz9BTss',
    appId: '1:165484821166:ios:a2481d630f5dc27b204b3f',
    messagingSenderId: '165484821166',
    projectId: 'flutter-chatbot-ia',
    storageBucket: 'flutter-chatbot-ia.firebasestorage.app',
    iosBundleId: 'com.example.chatbotIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAASZP2BLI48gopNo8OC-06oZYWruttOMc',
    appId: '1:165484821166:web:227b90639c8bf345204b3f',
    messagingSenderId: '165484821166',
    projectId: 'flutter-chatbot-ia',
    authDomain: 'flutter-chatbot-ia.firebaseapp.com',
    storageBucket: 'flutter-chatbot-ia.firebasestorage.app',
  );
}
